
<h2 class='text-center span12'>TOP DES CHARTS</h2>
<div class="row">	
	<ul class='unstyled span8 offset1'>
		<?php require('apps/topCharts.php'); ?>
	</ul>	
</div>
<p class="text-right span8 offset1 lead">
	Pour voir la liste des vinyles en vente
	<a href="index.php?page=store&section=list&search=vinyl"> >>> </a>
</p>


<h2 class='text-center span12'>LE MEILLEUR DES NOUVEAUTEES</h2>
<div class="row">	
	<ul class='unstyled span8 offset1'>
		<?php require('apps/topNew.php'); ?>
	</ul>
</div>
<p class="text-right span8 offset1 lead">
	Pour plus de nouveaut&eacute;
	<a href="index.php?page=store&section=list&search=new"> >>> </a>
</p>
