<div class="row span10 offset1">
	<figure>
		<img class="img-polaroid span6" src="sources/img/platine/<?=$article['img']?>.jpg" alt="<?=$article['nom']?>">

		<figcaption class="pull-right span6">
			<h4>NOM: <?=$article['nom']?></h4>
			<p><strong>ANNEE: <?=$article['annee']?> </strong> <br>
				MARQUE: <?=$article['marque']?></p>
			<p><?=$article['brefDescriptif']?></p>	
			<h6>Disponibilit&eacute;: <?=$article['stock']?> en stock</h6>
		</figcaption>

	</figure>
</div>
<div class="row span8 offset2">
	<?=$article['ficheTechnique']?>
</div>

<div class="row span8 offset2">
	<p class="span6 text-center lead">Prix TCC : <?=$article['prixTTC']?> &euro;</p>
		
	<form class="span6"action="skel.php" method="POST">
		<input type="hidden" name="id" value="<?=$article['id']?>" >
		<button type="submit" name="info" class="btn btn-inverse">Ajouter au Panier</button>
	</form>	
</div>