<h4>Clients</h4>
<table class="table" title="Client List">
    <tr>
        <th>Client ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>E-mail</th>
        <th>Address</th>
        <th>Town</th>
        <th>Zip code</th>
        <th>Birth Date</th>
        <th>Is Admin?</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php
    $i=0;
    while (isset($clients[$i])) {?>
    <tr>
        <td><?=$clients[$i]->getId()?></td>
        <td><?=$clients[$i]->getFirstName()?></td>
        <td><?=$clients[$i]->getName()?></td>
        <td><?=$clients[$i]->getEmail()?></td>
        <td><?=$clients[$i]->getAddress()?></td>
        <td><?=$clients[$i]->getVille()?></td>
        <td><?=$clients[$i]->getCodePostal()?></td>
        <td><?=$clients[$i]->getBirthdate()?></td>
        <td><?=$clients[$i]->getIsAdmin()?></td>
        <td><a href="#">Modify</a></td>
        <td><a href="#">Delete entry</a></td>
    </tr>
    <?php
        $i++;
    }
    ?>
</table>

<h4>Requêtes Client</h4>
<table class='table table-striped'>
	<thead>
		<tr>
			<th>Nom</th>
			<th>Prénom</th>
			<th>Email</th>
			<th>Demande par Artiste</th>
			<th>Demande par Titre</th>
			<th>Demande par Url</th>
			<th>Demande par Descriptif</th>
			<th>Date de la demande</th>
			<th>Envoyer un email</th>
			<th>Traité</th>
		</tr>
	</thead>
	<tbody>
		<?php require('apps/backendRequestClient.php');?>
	</tbody>
</table>
