<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">  
            <img class='span1' src="sources/img/logo1.jpg" alt="logo">
             
            <ul class="nav">
                <li class="divider-vertical">
                    <a href="index.php?backendpage=backendOrder">Commandes Client</a>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?backendpage=backendStock">Gestion des Stocks</a>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?backendpage=backendClient">Client</a>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?backendpage=backendAdmin">Gestion des Droits</a>
                </li>
                <li><a href="index.php?logOut=yes">D&eacute;connexion</a></li>
            </ul>  
           
        </div>
    </div>
</div>

