<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Vinyle &amp; Co</title>
    <link rel="icon" href="sources/img/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="sources/css/bootstrap.css">
    <link rel="stylesheet" href="sources/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="sources/css/animate.css">
    <link rel="stylesheet" href="sources/css/font-awesome.css">
    <link rel="stylesheet" href="sources/css/backstylesheet.css">
    <script src="sources/js/jquery.js"></script>
    <script src="sources/js/script.js"></script>
  	<script src="sources/js/bootstrap.js"></script>
  </head>
  
  <body>

    <div id="container-fluid" class="content page">
      
      <nav class="container">
        <?php require('apps/backendNav.php');?>
      </nav>
    
      <div class="container span10">
        <section id="page" class=''>
          <?php require('apps/'.$backendpage.'.php');?>   
        </section>
      </div>
             
      <footer class="container">
        <?php require('apps/footer.php');?>
      </footer>

    </div> 

	</body>

  <script src="sources/js/script.js"></script>
  
</html>


