<!--       Tableau des clients       -->
<h3>Clients</h3>
<table class="table" title="Client List">
    <tr>
        <th>Client ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>E-mail</th>
        <th>Address</th>
        <th>Town</th>
        <th>Zip code</th>
        <th>Birth Date</th>
        <th>Is Admin?</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php
    $i=0;
    while (isset($clients[$i])) {?>
    <tr>
        <td><?=$clients[$i]->getId()?></td>
        <td><?=$clients[$i]->getFirstName()?></td>
        <td><?=$clients[$i]->getName()?></td>
        <td><?=$clients[$i]->getEmail()?></td>
        <td><?=$clients[$i]->getAddress()?></td>
        <td><?=$clients[$i]->getVille()?></td>
        <td><?=$clients[$i]->getCodePostal()?></td>
        <td><?=$clients[$i]->getBirthdate()?></td>
        <td><?=$clients[$i]->getIsAdmin()?></td>
        <td><a href="#">Modify</a></td>
        <td><a href="#">Delete entry</a></td>
    </tr>
    <?php
        $i++;
    }
    ?>
</table>

<!--       Tableau des vinyles      -->
<h3>Vinyls</h3>
<table class="table" title="Vinyl List">
    <tr>
        <th>Article ID</th>
        <th>Artist</th>
        <th>Nom</th>
        <th>Year</th>
        <th>Style</th>
        <th>Prix TTC</th>
        <th>Tracks side A</th>
        <th>Tracks side B</th>
        <th>Label</th>
        <th>Cover</th>
        <th>Stock</th>
        <th>Brand</th>
        <th>Technical Details</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php
    $i=0;
    while (isset($vinyls[$i])) {?>
    <tr>
        <td><?=$vinyls[$i]->getId()?></td>
        <td><?=$vinyls[$i]->getArtiste()?></td>
        <td><?=$vinyls[$i]->getNom()?></td>
        <td><?=$vinyls[$i]->getAnnee()?></td>
        <td><?=$vinyls[$i]->getStyle()?></td>
        <td><?=$vinyls[$i]->getPrixTTC()?></td>
        <td><?=$vinyls[$i]->getTracksFaceA()?></td>
        <td><?=$vinyls[$i]->getTracksFaceB()?></td>
        <td><?=$vinyls[$i]->getLabel()?></td>
        <td><img src="../sources/img/vinyl_1680.jpg" width="50%"/></td>
        <td><?=$vinyls[$i]->getStock()?></td>
        <td><?=$vinyls[$i]->getMarque()?></td>
        <td><?=$vinyls[$i]->getDescription()?></td>
        <td><a href="#">Modify</a></td>
        <td><a href="#">Delete entry</a></td>
    </tr>
    <?php
        $i++;
    }
    ?>
</table>



<!--       Tableau des platines       -->

<h3>Platines</h3>

<table class="table" title="Platine List">
    <tr>
        <th>Article ID</th>
        <th>Nom</th>
        <th>Year</th>
        <th>Prix TTC</th>
        <th>Preview</th>
        <th>Stock</th>
        <th>Brand</th>
        <th>Technical Details</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php
    $i=0;
    while (isset($platines[$i])) {?>
    <tr>
        <td><?=$platines[$i]->getId()?></td>
        <td><?=$platines[$i]->getName()?></td>
        <td><?=$platines[$i]->getBirthdate()?></td>
        <td><?=$platines[$i]->getIsAdmin()?></td>
        <td><?=$platines[$i]->getIsAdmin()?></td>
        <td><?=$platines[$i]->getIsAdmin()?></td>
        <td><?=$platines[$i]->getIsAdmin()?></td>
        <td><?=$platines[$i]->getIsAdmin()?></td>
        <td><a href="#">Modify</a></td>
        <td><a href="#">Delete entry</a></td>
    </tr>
    <?php
        $i++;
    }
    ?>
</table>