<table>
    <tr>
        <th>Client ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>E-mail</th>
        <th>Address</th>
        <th>Town</th>
        <th>Zip code</th>
        <th>Birth Date</th>
        <th>Is Admin?</th>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    


</table>


    <?=$clients[0]->getEmail()?>
   <!-- <form action="apps/backend.php">
    </form>-->