<h3>Vinyls</h3>
<table class="table" title="Vinyl List">
    <tr>
        <th>Article ID</th>
        <th>Artist</th>
        <th>Nom</th>
        <th>Year</th>
        <th>Style</th>
        <th>Prix TTC</th>
        <th>Tracks side A</th>
        <th>Tracks side B</th>
        <th>Label</th>
        <th>Cover</th>
        <th>Stock</th>
        <th>Technical Details</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php $i=0;
    while (isset($vinyls[$i])) { ?>

    
    <tr class="togglemodvinyls defaulthidden">        
<form name="formmodifyvinyl" action="index.php?admin=ok&backendpage=backendStock" method="POST">
<td><?=$vinyls[$i]->getId()?>
    <input type="hidden" name="id" type="text" value="<?=$vinyls[$i]->getId()?>"></td>
<td><input name="artist" type="text" value="<?=$vinyls[$i]->getArtiste()?>"></td>
<td><input name="name" type="text" value="<?=$vinyls[$i]->getNom()?>"></td>
<td><input name="year" type="text" value="<?=$vinyls[$i]->getAnnee()?>"></td>
<td><input name="style" type="text" value="<?=$vinyls[$i]->getStyle()?>"></td>
<td><input name="prixTTC" type="text" value="<?=$vinyls[$i]->getPrixTTC()
?>"></td>
<td><input name="tracksA" type="text" value="<?=$vinyls[$i]->getTracksFaceA()?>"></td>
<td><input name="tracksB" type="text" value="<?=$vinyls[$i]->getTracksFaceB()?>"></td>
<td><input name="label" type="text" value="<?=$vinyls[$i]->getLabel()?>"></td>
<td><input name="cover" type="image" value="<?=$vinyls[$i]->GetCheminImg()?>"></td>
<td><input name="stock" type="text" value="<?=$vinyls[$i]->getStock()?>"></td>
<td><input name="description" type="text" value="<?=$vinyls[$i]->getDescription()?>"></td>
<td><input name="validate-vinyls" type="submit" class="btn" value="Valider" /></td>
<td><input name="delete-vinyl" type="button" class="btn btn-warning" value="Delete Entry" /></td>
</form>
    </tr>
    

   
    <tr class="togglemodvinyls">
        <td><?=$vinyls[$i]->getId()?></td>
        <td><?=$vinyls[$i]->getArtiste()?></td>
        <td><?=$vinyls[$i]->getNom()?></td>
        <td><?=$vinyls[$i]->getAnnee()?></td>
        <td><?=$vinyls[$i]->getStyle()?></td>
        <td><?=$vinyls[$i]->getPrixTTC()?></td>
        <td><?=$vinyls[$i]->getTracksFaceA()?></td>
        <td><?=$vinyls[$i]->getTracksFaceB()?></td>
        <td><?=$vinyls[$i]->getLabel()?></td>
        <td><?=$vinyls[$i]->getLabel()?></td>
        <td><img src="<?=$vinyls[$i]->GetCheminImg()?>"></td>
        <td><?=$vinyls[$i]->getDescription()?></td>
        <td><input name="modify-vinyls" type="button" class="btn modifyvinyls" value="Modify" /></td>
        <td>
            <form action="index.php?admin=ok&backendpage=backendStock" method="POST">
                <input name="delete-vinyl" type="submit" class="btn btn-warning" value="Delete Entry" />
                <input type="hidden" name='id' value='<?=$vinyls[$i]->getId()?>'>
            </form>
            </td>
    </tr>



    <?php $i++; } ?>
</table>

<!--       Tableau des platines       -->


<h3>Platines</h3>

<table class="table" title="Platine List">
    <tr>
        <th>Article ID</th>
        <th>Nom</th>
        <th>Year</th>
        <th>Prix TTC</th>
        <th>Preview</th>
        <th>Stock</th>
        <th>Brand</th>
        <th>Technical Details</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    <?php $i=0;
        while (isset($platines[$i])) {?>

<tr class="togglemodplatines defaulthidden">        
<form name="formmodifyplatines" action="index.php?admin=ok&backendpage=backendStock" method="POST">
<td><?=$platines[$i]->getId()?>
    <input type="hidden" name="id" type="text" value="<?=$platines[$i]->getId()?>"></td>
<td><input name="name" type="text" value="<?=$platines[$i]->getNom()?>"></td>
<td><input name="year" type="text" value="<?=$platines[$i]->getAnnee()?>"></td>
<td><input name="prixTTC" type="text" value="<?=$platines[$i]->getPrixTTC()
?>"></td>
<td><input name="description" type="text" value="<?=$platines[$i]->getDescription()?>"></td>
<td><input name="stock" type="text" value="<?=$platines[$i]->getStock()?>"></td>
<td><input name="brand" type="text" value="<?=$platines[$i]->getMarque()?>"></td>
<td><input name="validate-platines" type="submit" class="btn" value="Valider" /></td>
<td><input name="delete-platine" type="button" class="btn btn-warning" value="Delete Entry" /></td>
</form>
    </tr>





            <tr class="togglemodplatines">
                <td><?=$platines[$i]->getId()?></td>
                <td><?=$platines[$i]->getNom()?></td>
                <td><?=$platines[$i]->getAnnee()?></td>
                <td><?=$platines[$i]->getPrixTTC()?></td>
                <td><?=$platines[$i]->getDescription()?></td>
                <td><?=$platines[$i]->getStock()?></td>
                <td><?=$platines[$i]->getMarque()?></td>
                <td><?=$platines[$i]->getFicheTechnique()?></td>
                <td><input name="modify-platines" type="button" class="btn modifyplatines" value="Modify" /></td>
                <td>
                    <form action="index.php?admin=ok&backendpage=backendStock" method="POST">
                <input name="delete-platine" type="submit" class="btn btn-warning" value="Delete Entry" />
                <input type="hidden" name='id' value='<?=$platines[$i]->getId()?>'>
            </form>
                </td>
            </tr>
    <?php $i++; } ?>
</table>