<div class="contact">
	<p>
		Vinyle &amp; Co<br>
		Num&eacute;ro: 01 55 56 66 67<br>
		Adresse: 6, rue de l'&eacute;v&ecirc;nement 75006 Paris<br>
		Horaires: Du lundi au vendredi de 9h &agrave; 18h et le samedi de 10h &agrave; 19h.
	</p>
</div>



<form action="contact.php" method="POST" title="&Agrave; remplir">

<fieldset>		<legend>Produit non-propos&eacute; que vous d&eacute;sirer trouver</legend>
			
			<input type="text" name="artiste-voulu" placeholder="artiste.." required>
			
			<input type="text" name="titre-voulu" placeholder="titre.." required>
			
			<input type="text"name="url-voulu" placeholder="Url..">
			
			<textarea name="description-voulu" placeholder="description"></textarea>
			
			<input type="submit" name="submit-voulu" value="Envoyer">


</fieldset>
</form