<form action="index.php?logIn.php" method="POST">
	<label for="email"></label><input type="text" name="email" placeholder="Email"/>
	<br />
	<input type="password" name="password" placeholder="Mot de Passe"/>
	<br />
	<input type="date" name="birthdate" placeholder="jj/mm/aaaa"/>
	<br />
	<input type="text" name="address" placeholder="Adresse"/>
	<br />
	<input type="text" name="code" placeholder="Code Postal"/>
	<br />
	<input type="text" name="ville" placeholder="Ville"/>
	<br />

	<input type="submit" value="Validate" name="submit"/>
</form>
