<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="index.php?page=contact">
                <img src="sources/img/logo1.jpg" alt="logo">
            </a>
            <ul class="nav pull-right">
                <li class="divider-vertical dropdown">
                    <?php require("apps/".$navSection.".php");?>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?page=panier">Panier</a>
                </li>
            </ul>
             
            <ul class="nav pull-left">
                <li class="divider-vertical">
                    <a href="index.php?page=accueil">Accueil</a>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?page=store&section=list&search=new">Nouveaut&eacutes</a>
                </li>
                <li class="divider-vertical">
                    <a href="index.php?page=store&section=list&search=platine">Platines</a>
                </li>
                <li class="divider-vertical dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Vinyles 
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <?php require("apps/categorie.php");?>
                        <li><a href="index.php?page=store&section=list&search=vinyl">Tous</a></li>
                    </ul>
                </li>
            </ul>  
             <form class="navbar-search pull-right">
                    <input type="text" class="search-query" placeholder="Search">
            </form>  
        </div>
    </div>
</div>

