<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Bonjour <?=$_SESSION['login']?>
    <b class="caret"></b>
</a>
<div id="logInForm" class="dropdown-menu box">
	<form action="index.php?nav=nav&navSection=navlogIn" method="POST">
		<input type="submit" name="f_out" value="LogOut" class="btn btn-mini btn-danger">
	</form>
	<a href="index.php?admin=ok"><button class="btn btn-mini btn-success">Entrer dans le BackOffice</button></a>
</div>
<div  class="dropdown-menu box">
</div>