<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Mon Compte
    <b class="caret"></b>
</a>

<div id="logInForm" class="dropdown-menu box">
    <form  action='index.php?nav=nav&navSection=navlogIn' method="post">
        <input type="email" class="input-small marg" name="email" placeholder="Email">
        <input type="password" class="input-small marg" name="password" placeholder="Password">
        <button type="submit" class="btn btn-inverse btn-mini pull-right">OK</button>
    </form>
    <p> <?=$error?> </p>
    <p> 
        Pas encore inscrit ?                
        <a href="index.php?page=logIn"><button class="btn btn-mini btn-success">C&eacute;er un compte</button></a>
    </p>
</div>