<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Bonjour <?=$_SESSION['login']?>
    <b class="caret"></b>
</a>
<ul class="dropdown-menu">
    <li><a href="index.php?page=commande">Suivi de Commande</a></li>
    <li><a href="index.php?page=contact">Demande Particuli&egrave;re</a></li>
    <li class="divider"></li>
    <li><a href="index.php?logOut=yes">D&eacute;connexion</a></li>
</ul>
