<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Article</th>
			<th>Descriptif</th>
			<th>Prix</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php require('apps/articlePanier.php');?>
	</tbody>
</table>
<table>
	<tr>
		<th>TOTAL HT</th>
		<td><?=$_SESSION['TotalHT']?></td>
	</tr>
	<tr>
		<th>TOTAL TVA</th>
		<td><?=$_SESSION['TotalTva']?></td>	
	</tr>
	<tr>
		<th>TOTAL TTC</th>
		<td><?=$_SESSION['TotalTTC']?></td>
	</tr>
</table>
