<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Article</th>
			<th>Descriptif</th>
			<th>Prix</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php require('apps/articlePanier.php');?>
	</tbody>
</table>
<table class="table">
	<tr>
		<th class="span5">TOTAL HT</th>
		<td class="span2 text-right"><?=$_SESSION['TotalHT']?> &euro;</td>
	</tr>
	<tr>
		<th class="span5">TOTAL TVA</th>
		<td class="span2 text-right"><?=$_SESSION['TotalTva']?> &euro;</td>	
	</tr>
	<tr>
		<th class="span5">TOTAL TTC</th>
		<td class="span2 text-right"><?=$_SESSION['TotalTTC']?> &euro;</td>
	</tr>
</table>

<div class="">
	
</div>

<form class="pull-right" action="index.php?page=panier" method="POST">
	<button class="btn btn-success" type="submit">Passer Commande</button>
</form>