<div class="row">
	<form class="form-horizontal span10 offset1" action="index.php?page=contact" method="POST" >

		<fieldset>		
			<legend><h4>Produit non-propos&eacute; que vous d&eacute;sirer trouver</h4></legend>
			<div class="control-group">
				<label class="control-label" for="artisteVoulu"><i class="fa fa-file-image-o fa-fw"></i></label>
				<div class="controls">	
					<input class="span8" type="text" name="artisteVoulu" placeholder="Artiste..." required>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="titreVoulu"><i class="fa fa-play-circle fa-fw"></i></label>
				<div class="controls">		
					<input class="span8" type="text" name="titreVoulu" placeholder="Titre..." required>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="urlVoulu"><i class="fa fa-file-code-o fa-fw"></i></label>
				<div class="controls">
					<input class="span8" type="text"name="urlVoulu" placeholder="Copier l'Url du titre que vous souhaitez...">
				</div>
			</div>
			
			<div class="control-group">
				<label class="control-label" for="descriptionVoulu"><i class="fa fa-file-text-o fa-fw"></i></label>
				<div class="controls">	
					<textarea class="span8" name="descriptionVoulu" placeholder="Donnez-nous plus de pr&eacute;cisions sur le vinyle que vous recherchez...." rows="3"></textarea>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">	
					<i class="fa fa-paper-plane-o"></i><input class="btn btn-inverse pull-right" type="submit" name="submitVoulu" value="Envoyer">
				</div>
			</div>
			<p><?=$requetenvoyee?></p>
		</fieldset>

	</form>
</div>