<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<title>Vinyle &amp; Co</title>
    <link rel="icon" href="sources/img/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="sources/css/bootstrap.css">
    <link rel="stylesheet" href="sources/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="sources/css/stylesheet.css">
    <link rel="stylesheet" href="sources/css/animate.css">
    <link rel="stylesheet" href="sources/css/font-awesome.css">
    <script src="sources/js/jquery.js"></script>
  	<script src="sources/js/bootstrap.js"></script>
  </head>
  
  <body>
  <div class="content">

    <header class="container">
      <?php require('apps/header.php'); ?>
    </header>

    <nav class="container">
      <?php require('apps/nav.php'); ?>
    </nav>

    <section class='container'>
      <?php require('apps/'.$page.'.php'); ?>	
		</section>
		
    <footer class="container">
      <?php require('apps/footer.php'); ?>
	  </footer>

  </div>
	</body>
  <script src="sources/js/script.js"></script>
</html>


